### PR TITLE
Feature/symfony3

### PR DESCRIPTION
**Pull request by pikkart**
* updated composer requirements to allow symfony 3 components as well
** UniversalClassLoader was removed in symfony3; refactored that part in favor for "ClassLoader" class
* fixed some minor method name mismatches

### CODE REVIEW

**Comment by amyboyd** [comment]
Thanks -- I'll check this out soon.

To be honest, this project in it's current form is a bit dead to me. Building a CLI tool in PHP was a mistake due to the PHP dependency on MongoDB servers. I'm thinking of a rewrite in a more distributable language like Go/Python. But I'll review this PR anyway.

**Comment by pikkart** [comment]
Thanks for the quick reply! 
We still have it in use (and I think some more people do as well, at least judging from packagist stats) and are in the middle of the migration from symfony 2.x to 3.x (and later update to PHP 7)

Since it fails with travis tests due to PHPUnit requirements for at least PHP 5.6: Should I increase the minimum requirement to PHP >= 5.6 in composer.json and drop travis env with PHP 5.5 (which 
 already reached its EOL)?

**Comment by amyboyd** [comment]
Min 5.6 makes sense. Thanks!

**Comment by amyboyd** [comment]
Thanks a lot -- merged!

I've also added you as a contributor to the repositories. If you/your team want to make PRs, you'll be able to merge.

**Comment by pikkart** [comment]
Great, thanks!
Just for my curiosity: is there a reason for not tagging it (with 1.7.4)? 
Though this would also require an update of mongrate-bundle to be compatible with symfony 3. Should I provide it?

**Pull request merged**
