### PR TITLE
#44 - Add Direction enum

### LINKED ISSUE #44: Add DirectionEnum to have all available directions
This will avoid having so many hardcoded string like `up` and `down`

And we have a way to get all available directions.

### PR DESCRIPTION
**Pull request by BernardoSilva**
This ticket closes #44 
- [x] Add BaseEnum class.
- [x] Add DirectionEnum class.
- [x] Add unit tests for Direction Model.
- [x] Refactor code for hardcoded directions.

### CODE REVIEW

**Comment by amyboyd** [comment]
+1. Do you think it's worth refactoring `BaseEnum` to a `partnermarketing/enum` package, @BernardoSilva ?

**Comment by BernardoSilva** [comment]
I was thinking about it.
But then I did a quick research, why not we start using this?

https://github.com/myclabs/php-enum it has loads of downloads on [packagist](https://packagist.org/packages/myclabs/php-enum) and is maintained, we could use it and help maintain if needed.

What you think @amyboyd ?

**Comment by amyboyd** [comment]
Maybe. My only worry is we might want to extend a base enum class in a way pm.com thinks is useful, not in a way `myclabs` thinks is useful, in the future. Let's discuss tomorrow, I'm too drunk to think straight now.

**Comment by amyboyd** [comment]
Although Mongrate isn't technically pm.com, so maybe.

**Pull request merged**
