### PR TITLE
Add command to sync all migration.

### LINKED ISSUE #34: Add command to apply all migrations if there is any not applied.
This command should apply all the migrations that are not applied yet.
This will be very useful for automation.
e.g.

On every deploy ensure all migrations are applied/sync.

### PR DESCRIPTION
**Pull request by BernardoSilva**
- [x] This command should apply all migrations when they are not applied yet.
- [x] Add test to ensure it find all the available migrations.
- [x] Add `Migration` data model.
- [x] fixes #34 

Dependency on #33 to be merged first.

### CODE REVIEW

**Comment by amyboyd** [comment]
The name "sync" doesn't make sense. For consistency I'd recommend "up-all" or "all-up".

**Comment by BernardoSilva** [comment]
Renamed command to `up-all`.
Don't like it much but not important for now... :)

**Comment by amyboyd** [comment]
The current implementation goes against one of the project's original goals:

`To be non-linear, so migrations can be applied in any order and at any time.`

**Comment by BernardoSilva** [comment]
What you mean by that? 
Current implementation does not enforce any order...
Apply migrations enforcing an order should be an optional parameter to enforce a specific order IMO.

**Comment by amyboyd** [comment]
@BernardoSilva You're right. I was looking at the wrong thing.

This refactoring PR moves many command methods to a service, so you can re-use some existing code instead of having to write it again in this command: https://github.com/mongrate/mongrate/pull/41

**Comment by amyboyd** [comment]
@BernardoSilva I was mixing up this PR and https://github.com/mongrate/mongrate/issues/39 - my bad.

**Comment by amyboyd** [comment]
Manually merged with some edits https://github.com/mongrate/mongrate/commits/master

**Pull request closed without merging**
